### ISSUE TITLE
Background lazyloading

### ISSUE THREAD

**Issue by VelociraptorCZE** [VelociraptorCZE/MiniLazyload#2]
### Description
This feature isn't supported yet, although it might be useful in certain cases.

### HTML example
```html
<div data-bg="background_source">
```

### Expected behavior
If data-bg attribute is present on the element, it'll add background-image with given source.

PR: https://github.com/VelociraptorCZE/MiniLazyload/pull/3/

**Comment by smety** [comment]
`data-bg` its ok, have libary fallback image in background?

**Comment by VelociraptorCZE** [comment]
> `data-bg` its ok, have libary fallback image in background?

I'm quite dubious if this is even possible.

**Comment by VelociraptorCZE** [comment]
> `data-bg` its ok, have libary fallback image in background?

I'm quite dubious if this is even possible to be done conveniently.

**Comment by VelociraptorCZE** [comment]
> `data-bg` its ok, have libary fallback image in background?

I'm quite dubious if this can be done conveniently.

**Comment by VelociraptorCZE** [comment]
New version was deployed to NPM with background lazyloading.
