### ISSUE TITLE
Does lazyloading work on an element created programmatically?

### ISSUE THREAD

**Issue by fosil** [VelociraptorCZE/MiniLazyload#7]
I tried about this:

```
// HTML code
<img data-for-lazy-load="http://domain.com/path/to/image.jpg" ... id="image" />

// JS (running approx. 2000 ms after document.ready)
var $img = jQuery('#image');
$img.attr('src-dist', $img.attr('data-for-lazy-load'))
    .attr("loading", "lazy");
```

... but lazy loading won't start

I'm doing something wrong?
Thx

**Comment by VelociraptorCZE** [comment]
This issue isn't regarding my library but I'll answer.

The correct approach should be this:

```js
var img = $("#image");
img.attr("src", img.data("for-lazy-load")).attr("loading", "lazy");
```

**Comment by fosil** [comment]
But I'm using your library and testing it on a browser that doesn't support native lazyloading. Elements in html specified according to documentation syntax work, but dynamically created image does not.

**Comment by VelociraptorCZE** [comment]
Alright, good point, however this isn't supported at all. You have to basically call **update** method every time you need to or use MutationObserver.

```js
const lazyload = new MiniLazyload({}, '.lazyload');

// somewhere else ...

// just a quick example
const img = new Image;
img.className = "lazyload";
img.dataset.src = "/path/image.png";
document.body.insertAdjacentElement("beforeend", img);

// then call update method
lazyload.update();
```

If you have some other problems with this, just let me know and I'll try to help you. :)

**Comment by fosil** [comment]
That was exactly what I was interested in! If there is an update (reinit, register, ...) method that would "register" a new element. I just want to be sure: the img element should have the .lazyload class (or the corresponding selector)?

Thanks a lot for your answers!

**Comment by VelociraptorCZE** [comment]
Yeah, I forgot to add a "lazyload" to img's class in my example, :D images are selected through selector passed in the constructor. :)

**Comment by fosil** [comment]
I thought so, but I wanted to be sure.
Thanks again for your help (and especially for this lib!)
